# -*- coding: utf-8 -*-
"""FootballPredictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F5-1uwPDMtKVwgUK-0SzwnpbOdFO4Mgg
"""

import pandas as pd
import numpy as np

data = pd.read_csv("/results.csv")

data

x=[]

for h,a in data.iterrows():
    
    if a['home_score'] > a['away_score']:
            x.append(1)
            
    elif a['home_score'] < a['away_score']:
            
            x.append(0)
    else:
        x.append(2)

#x

data=data.rename(columns={'date':'result'})

data

data['result']=x

###For analysis of how data actually is###
#Didnt help though lol XD #
import seaborn as sns


sns.pairplot(data)

data

data=data.loc[:,['result', 'home_team' , 'away_team' , 'home_score' , 'away_score' , 'country']]

data

array=data.loc[:,'home_team'].unique().copy()

#array contians all the names for dictionary
array

d1 = dict(enumerate(array.flatten(), 1))

d={key : value for (value,key) in d1.items()}

d

#it is printing the country name alphabetically but the mapping is done fine as per order in variable 'array'

data['home_team']=data['home_team'].map(d).values
data['away_team']=data['away_team'].map(d).values

data['country']=data['country'].map(d).values

data

#Since everything is with respect to home team , i decided to take goal difference as a label to predict and from that the result of the match could be predicted easily (+ve goal
# difference would symbolize a win for home team , -ve GD would symbolize a defeat for home team )
### EVERYTHING IS WITH RESPECT TO HOME TEAM FOR BETTER UNDERSTANDING ###


data['home_score'] = data['home_score']-data['away_score']


data=data.rename(columns={'home_score':'goal_diff'})

#filling nan values with average , it was later that i realized i could've predicted it using any regressor but i was in a hurry to complete it so i just put in averages
mean_home_team = data['home_team'].mean()
mean_away_team = data['away_team'].mean()
mean_country = data['country'].mean()
mean_score = data['goal_diff'].mean()


data['home_team'] = data['home_team'].fillna(mean_home_team)
data['away_team'] = data['away_team'].fillna(mean_away_team)
data['country'] = data['country'].fillna(mean_country)
data['goal_diff'] = data['goal_diff'].fillna(mean_score)

data

data['foal_diff'] = data['goal_diff'].values.astype('float')

data

###Splitting Data into Training and Test sets###

from sklearn.model_selection import train_test_split

X= data.loc[:,['home_team','away_team','country']].values.copy()
y= data['goal_diff'].values.copy()

print(X)
print(y)

X_train , X_test , y_train , y_test = train_test_split(X,y, test_size=0.3, random_state=1)

X_train.shape

X_test.shape

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(X_train)

X_train_std = sc.transform(X_train)

sc.fit(X_test)
X_test_std = sc.transform(X_test)

X_train_std

d

# x1 will show the match that is happening 
# this is an example where we play Germany(16) vs Finland(20) in Germany (mapped according to above dictionary) , clearly Ger should win as they're 
# stronger than Finland lets see if the predicted goal difference is positive



x1 = np.array([[16,20,16]])

x1_std = sc.transform(x1)
x1_std

from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor

#Below i used RandomizedSearchCV to find the best parameters for training , i saw this in a youtube video 

n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
print(n_estimators)

from sklearn.model_selection import RandomizedSearchCV

#Randomized Search CV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()

# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid,scoring='neg_mean_squared_error',
                               n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

rf_random.fit(X_train_std,y_train)

rf_random.predict(x1_std)

### above result shows that the home team (Germany) would have a goal difference of around 2.541 if they played Finland in Germany

pred = rf_random.predict(X_test_std)

import matplotlib.pyplot as plt


plt.scatter(y_test,pred)

#its not perfect but it is close i guess , the variance is high if im interpreting it correctly

#the gaussian, estimating bias, however looks fine

sns.distplot(y_test-pred)



